pipeline:
  identifier: testbfolly
  name: test-b-folly
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: folly
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        identifier: linux
        type: CI
        name: linux
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: fetch
                  type: Run
                  name: fetch
                  spec:
                    shell: Sh
                    command: python3 build/fbcode_builder/getdeps.py fetch --no-tests <+matrix.deps>
                  failureStrategies: []
                  strategy:
                    matrix:
                      deps:
                        - boost
                        - ninja
                        - cmake
                        - double-conversion
                        - fmt
                        - gflags
                        - glog
                        - googletest
                        - libevent
                        - lz4
                        - snappy
                        - zstd
                      maxConcurrency: 1
              - step:
                  identifier: build
                  type: Run
                  name: build
                  spec:
                    shell: Sh
                    command: python3 build/fbcode_builder/getdeps.py build --no-tests <+repeat.item>
                  failureStrategies: []
                  strategy:
                    repeat:
                      items:
                        - boost
                        - ninja
                        - cmake
                        - double-conversion
                        - fmt
                        - gflags
                        - glog
                        - googletest
                        - libevent
                        - lz4
                        - snappy
                        - zstd
                      maxConcurrency: 1
                  when:
                    stageStatus: All
              - step:
                  identifier: build_folly
                  type: Run
                  name: build folly
                  spec:
                    shell: Sh
                    command: python3 build/fbcode_builder/getdeps.py build --src-dir=. folly  --project-install-prefix folly:/usr/local
                  when:
                    stageStatus: All
                  failureStrategies: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
